#!/bin/sh 
case "$1" in
  start)
    echo "Starte diary..."
    read addr < config/spert/ip
    read port < config/spert/diary/port
    ./diary.pl $addr $port &
    ;;
  stop)
    echo "Beende diary..."
    killall diary.pl
    ;;
  *)
    echo "$0 {start|stop}"
    ;;
esac
