#!/bin/sh
BASE="`cat config/base`"
HTTPD=${BASE}/bin/httpd

case "$1" in
  start)
    echo "Starte httpd..."
    $HTTPD -f ${BASE}/httpd.conf
    ;;
  stop)
    echo "Beende httpd..."
    killall httpd
    ;;
  *)
    echo "$0 {start|stop}"
    ;;
esac
