#!/bin/sh
LOC="polizei prison sekte spert"
case "$1" in
  start)
    for loc in $LOC; do
        read device < config/${loc}/device
        read ip     < config/${loc}/ip
        ifconfig $device $ip up
    done
    ;;
  stop)
    for loc in $LOC; do
        read device < config/${loc}/device
        ifconfig $device down
    done
    ;;
  *)
    echo "$0 {start|stop}"
    ;;
esac
