#!/bin/sh 
case "$1" in
  start)
    echo "Starte polsys..."
    read addr < config/polizei/ip 
    read port < config/polizei/polsys/port
    touch polsys.txt
    ./polsys.pl $addr $port &
    ;;
  stop)
    echo "Beende polsys..."
    killall polsys.pl
    ;;
  *)
    echo "$0 {start|stop}"
    ;;
esac
