#!/bin/sh
case "$1" in
  start)
    echo "Starte uml..."
    cd uml
    screen -dmS "User Mode Linux" ./run-uml
    echo "gebe uml Zeit um zu booten..."
    sleep 30
    ;;
  stop)
    echo "Beende uml..."
    killall run-uml
    killall linux
    ;;
  *)
    echo "$0 {start|stop}"
    ;;
esac
