#!/bin/sh
case "$1" in
  start)
    echo "Starte uml..."
    echo "###################################################"
    echo "###################################################"
    echo "###################################################"
    echo
    echo "uml muss im moment manuell gestartet werden."
    echo 
    echo "###################################################"
    echo "###################################################"
    echo "###################################################"
    #(
    #    cd uml
    #    ./run-uml
    #) &
    ;;
  stop)
    echo "Beende uml..."
    killall run-uml
    killall linux
    ;;
  *)
    echo "$0 {start|stop}"
    ;;
esac
