#!/bin/sh
case "$1" in
    netstart)
        if [ $UID -ne 0 ]; then
            echo "nur als root"
            exit 1
        fi
        init/network start
        ;;
    netstop)
        if [ $UID -ne 0 ]; then
            echo "nur als root"
            exit 1
        fi
        init/network stop 
        ;;
    rootstart)
        init/uml-redir start
        init/httpd start 
        ;;
    rootstop)
        init/uml-redir stop 
        init/httpd stop
        ;;
    start)
        init/diary start 
        init/polsys start 
        init/p2p start 
        init/newsserver start 
        init/irc start
        echo "$0 umlstart als root nicht vergessen"
        ;;
    stop)
        init/diary stop
        init/polsys stop
        init/p2p stop
        init/newsserver stop
        init/irc stop
        echo "$0 umlstop als root nicht vergessen"
        ;;
    *)
        echo "$0 {nstart|nstop|start|stop}"
        ;;
esac        
