#!/bin/sh
case "$1" in
    nstart)
        if [ $UID -ne 0 ]; then
            echo "nur als root"
            exit 1
        fi
        init/network start
        ;;
    nstop)
        if [ $UID -ne 0 ]; then
            echo "nur als root"
            exit 1
        fi
        init/network stop 
        ;;
    umlstart)
        init/uml-redir start
        ;;
    umlstop)
        init/uml-redir stop 
        ;;
    start)
        init/httpd start 
        init/diary start 
        init/polsys start 
        init/p2p start 
        init/uml start 
        echo "$0 umlstart als root nicht vergessen"
        ;;
    stop)
        init/httpd stop
        init/diary stop
        init/polsys stop
        init/p2p stop
        init/uml stop
        echo "$0 umlstop als root nicht vergessen"
        ;;
    *)
        echo "$0 {nstart|nstop|start|stop}"
        ;;
esac        
